import json
import torch
import numpy as np
import argparse
import os
from esm2_feature_ex import ESMFeatureExtractor
from tqdm import tqdm

def process_dataset(json_path, out_pt_path):
    print(f"Loading dataset from {json_path}")
    with open(json_path, 'r') as f:
        raw_data = json.load(f)
        
    if isinstance(raw_data, dict):
        data = []
        for pid, bs_info in raw_data.items():
            item = dict(bs_info)
            item['protein_id'] = pid
            data.append(item)
    else:
        data = raw_data
        
    extractor = ESMFeatureExtractor()
    dataset = []
    
    # Podpora pro mapování na labely
    from Binding_site_ex import COFACTOR_FUNCTIONAL_GROUPS
    supported = list(COFACTOR_FUNCTIONAL_GROUPS.keys())
    
    for i, bs in enumerate(tqdm(data, desc="Extracting ESM features")):
        seq = bs.get('binding_site_sequence', '')
        if not seq:
            continue
            
        pid = bs.get('protein_id', f"unknown_{i}")
        if 'pocket' not in pid and 'pdb_file' in bs:
            # P2Rank format
            pid = bs['pdb_file'].replace('.pdb', '') + f"_pocket_{i}"
            
        lbl = int(bs.get('label', -1))
        if lbl == -1:
            act = bs.get('actual_ligand_name', '')
            if act in supported:
                lbl = supported.index(act)
                
        if lbl == -1:
            continue
            
        try:
            emb = extractor.extract_embeddings(seq) # [L, 1280]
            emb_tensor = torch.FloatTensor(emb).cpu()
            
            dataset.append({
                'protein_id': pid,
                'features': emb_tensor,
                'label': lbl,
                'pocket_id': bs.get('pocket_id', pid)
            })
        except Exception as e:
            print(f"Failed to extract for {pid}: {e}")
            
    print(f"Extracted features for {len(dataset)} binding sites.")
    torch.save(dataset, out_pt_path)
    print(f"Saved to {out_pt_path}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', default='p2rank_pockets_dataset.json', help='Input JSON generated by build_dataset.py')
    parser.add_argument('--output', default='esm_dataset.pt', help='Output PT file with extracted features')
    args = parser.parse_args()
    
    process_dataset(args.input, args.output)
